// Query TypeMap
import "@sanity/client";

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  aspectRatio?: number;
  height?: number;
  width?: number;
};

export type SanityFileAsset = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: "sanity.fileAsset";
  _updatedAt: string;
  altText?: string;
  assetId?: string;
  description?: string;
  extension?: string;
  label?: string;
  mimeType?: string;
  originalFilename?: string;
  path?: string;
  sha1hash?: string;
  size?: number;
  source?: SanityAssetSourceData;
  title?: string;
  uploadId?: string;
  url?: string;
};

export type Geopoint = {
  _type: "geopoint";
  alt?: number;
  lat?: number;
  lng?: number;
};

export type Projects = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: "projects";
  _updatedAt: string;
  description: string;
  image: {
    _type: "image";
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  link: string;
  name: string;
  repo?: string;
  slug: Slug;
};

export type Blogs = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: "blogs";
  _updatedAt: string;
  description: string;
  gallery?: Array<{
    _key: string;
    _type: "image";
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  }>;
  isPublished: boolean;
  poster: {
    _type: "image";
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  preview?: string;
  publishedAt: string;
  sendEmail?: string;
  slug: Slug;
  tags: Array<string>;
  text: Array<
    | {
        _key: string;
        _type: "block";
        children?: Array<{
          _key: string;
          _type: "span";
          marks?: Array<string>;
          text?: string;
        }>;
        level?: number;
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          _key: string;
          _type: "link";
          href?: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      }
    | {
        _key: string;
        _type: "image";
        alt?: string;
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
      }
    | ({
        _key: string;
      } & Code)
  >;
  title: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  bottom?: number;
  left?: number;
  right?: number;
  top?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  height?: number;
  width?: number;
  x?: number;
  y?: number;
};

export type SanityImageAsset = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: "sanity.imageAsset";
  _updatedAt: string;
  altText?: string;
  assetId?: string;
  description?: string;
  extension?: string;
  label?: string;
  metadata?: SanityImageMetadata;
  mimeType?: string;
  originalFilename?: string;
  path?: string;
  sha1hash?: string;
  size?: number;
  source?: SanityAssetSourceData;
  title?: string;
  uploadId?: string;
  url?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  id?: string;
  name?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  blurHash?: string;
  dimensions?: SanityImageDimensions;
  hasAlpha?: boolean;
  isOpaque?: boolean;
  location?: Geopoint;
  lqip?: string;
  palette?: SanityImagePalette;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Code = {
  _type: "code";
  code?: string;
  filename?: string;
  highlightedLines?: Array<number>;
  language?: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Projects
  | Blogs
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Slug
  | Code;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/utils.ts
// Variable: PROJECTS_QUERY
// Query: *[_type=='projects']|order(_createdAt desc){name,  "image": image.asset->url,      "imageMetadata": { "lqip": (image.asset->metadata).lqip, "dimensions": (image.asset->metadata).dimensions }, description, link, repo}
export type PROJECTS_QUERYResult = Array<{
  description: string;
  image: string | null;
  imageMetadata: {
    dimensions: SanityImageDimensions | null;
    lqip: string | null;
  };
  link: string;
  name: string;
  repo: string | null;
}>;
// Variable: BLOGS_POSTS_QUERY
// Query: *[_type=='blogs' && isPublished]|order(publishedAt desc)  {title,  _createdAt, _updatedAt, "poster": poster.asset->url,  "posterMetadata": { "lqip": (poster.asset->metadata).lqip, "dimensions": (poster.asset->metadata).dimensions },   publishedAt, "slug": slug.current, description}
export type BLOGS_POSTS_QUERYResult = Array<{
  _createdAt: string;
  _updatedAt: string;
  description: string;
  poster: string | null;
  posterMetadata: {
    dimensions: SanityImageDimensions | null;
    lqip: string | null;
  };
  publishedAt: string;
  slug: string;
  title: string;
}>;
// Variable: BLOG_POST_QUERY
// Query: *[_type=='blogs' && slug.current==$slug && isPublished]{title, "plainText": title + pt::text(text) + description,   "poster": poster.asset->url, "posterLqip": (poster.asset->metadata).lqip, publishedAt, isPublished,   "gallery": gallery[]{ "image": asset->url, "lqip": asset->metadata.lqip }, tags, _updatedAt, "text": text[]   {..., ...select( _type == "image" => { "image": asset->url, "lqip": (asset->metadata).lqip } ) },   "slug": slug.current,_createdAt, description}[0]
export type BLOG_POST_QUERYResult = {
  _createdAt: string;
  _updatedAt: string;
  description: string;
  gallery: Array<{
    image: string | null;
    lqip: string | null;
  }> | null;
  isPublished: boolean;
  plainText: string;
  poster: string | null;
  posterLqip: string | null;
  publishedAt: string;
  slug: string;
  tags: Array<string>;
  text: Array<
    | {
        _key: string;
        _type: "block";
        children?: Array<{
          _key: string;
          _type: "span";
          marks?: Array<string>;
          text?: string;
        }>;
        level?: number;
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          _key: string;
          _type: "link";
          href?: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      }
    | {
        _key: string;
        _type: "code";
        code?: string;
        filename?: string;
        highlightedLines?: Array<number>;
        language?: string;
      }
    | {
        _key: string;
        _type: "image";
        alt?: string;
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
        image: string | null;
        lqip: string | null;
      }
  >;
  title: string;
} | null;
// Variable: BLOG_POSTS_PREVIEW_QUERY
// Query: *[_type=='blogs' && isPublished]|order(publishedAt desc)  {title,  _createdAt, _updatedAt, "poster": poster.asset->url,  "posterMetadata": { "lqip": (poster.asset->metadata).lqip, "dimensions": (poster.asset->metadata).dimensions },   publishedAt, "slug": slug.current, description}
export type BLOG_POSTS_PREVIEW_QUERYResult = Array<{
  _createdAt: string;
  _updatedAt: string;
  description: string;
  poster: string | null;
  posterMetadata: {
    dimensions: SanityImageDimensions | null;
    lqip: string | null;
  };
  publishedAt: string;
  slug: string;
  title: string;
}>;
// Variable: BLOG_POST_PREVIEW_QUERY
// Query: *[_type=='blogs' && slug.current==$slug]{title, "plainText": title + pt::text(text) + description,     "poster": poster.asset->url, "posterLqip": (poster.asset->metadata).lqip, publishedAt, isPublished,     "gallery": gallery[]{ "image": asset->url, "lqip": asset->metadata.lqip }, tags, _updatedAt, "text": text[]     {..., ...select( _type == "image" => { "image": asset->url, "lqip": (asset->metadata).lqip } ) },    "slug": slug.current,_createdAt, description}[0]
export type BLOG_POST_PREVIEW_QUERYResult = {
  _createdAt: string;
  _updatedAt: string;
  description: string;
  gallery: Array<{
    image: string | null;
    lqip: string | null;
  }> | null;
  isPublished: boolean;
  plainText: string;
  poster: string | null;
  posterLqip: string | null;
  publishedAt: string;
  slug: string;
  tags: Array<string>;
  text: Array<
    | {
        _key: string;
        _type: "block";
        children?: Array<{
          _key: string;
          _type: "span";
          marks?: Array<string>;
          text?: string;
        }>;
        level?: number;
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          _key: string;
          _type: "link";
          href?: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      }
    | {
        _key: string;
        _type: "code";
        code?: string;
        filename?: string;
        highlightedLines?: Array<number>;
        language?: string;
      }
    | {
        _key: string;
        _type: "image";
        alt?: string;
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
        image: string | null;
        lqip: string | null;
      }
  >;
  title: string;
} | null;

declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type==\'projects\']|order(_createdAt desc){name,  "image": image.asset->url,    \n  "imageMetadata": { "lqip": (image.asset->metadata).lqip, "dimensions": (image.asset->metadata).dimensions }, description, link, repo}': PROJECTS_QUERYResult;
    '*[_type==\'blogs\' && isPublished]|order(publishedAt desc)\n  {title,  _createdAt, _updatedAt, "poster": poster.asset->url,\n  "posterMetadata": { "lqip": (poster.asset->metadata).lqip, "dimensions": (poster.asset->metadata).dimensions }, \n  publishedAt, "slug": slug.current, description}':
      | BLOGS_POSTS_QUERYResult
      | BLOG_POSTS_PREVIEW_QUERYResult;
    '*[_type==\'blogs\' && slug.current==$slug && isPublished]{title, "plainText": title + pt::text(text) + description, \n  "poster": poster.asset->url, "posterLqip": (poster.asset->metadata).lqip, publishedAt, isPublished, \n  "gallery": gallery[]{ "image": asset->url, "lqip": asset->metadata.lqip }, tags, _updatedAt, "text": text[] \n  {..., ...select( _type == "image" => { "image": asset->url, "lqip": (asset->metadata).lqip } ) },\n   "slug": slug.current,_createdAt, description}[0]': BLOG_POST_QUERYResult;
    '*[_type==\'blogs\' && slug.current==$slug]{title, "plainText": title + pt::text(text) + description, \n    "poster": poster.asset->url, "posterLqip": (poster.asset->metadata).lqip, publishedAt, isPublished, \n    "gallery": gallery[]{ "image": asset->url, "lqip": asset->metadata.lqip }, tags, _updatedAt, "text": text[] \n    {..., ...select( _type == "image" => { "image": asset->url, "lqip": (asset->metadata).lqip } ) },\n    "slug": slug.current,_createdAt, description}[0]': BLOG_POST_PREVIEW_QUERYResult;
  }
}
